apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXItcmVwb3NpdG9yeS5waWtsZW1hLmNvbSI6IHsKCQkJImF1dGgiOiAiYVcxaFoyVXRjSFZzYkdWeU9uTnZjMUJTVDBSUVNVdE1SVTFCTjJoaGEyZGpkWGhxYzNObmRUZzFkemRoT1dObWNqbHpaSFZqTkhweWVYVmxiM009IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIlZtbGpVMmgyWldRNloyaHdYMGhpVG05MGRFUlhjbGh5V1hZMWVXaDZVMEV5YUVkb1UzTlRZbnBsZGpKWFVsUnZZUT09IgoJCX0KCX0sCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0sCgkJImFpIjogewoJCQkiaG9va3MiOiAiYnVpbGQsYnVpbGR4IGJ1aWxkLHJ1bixjb21wb3NlIgoJCX0sCgkJImNvbXBvc2UiOiB7CgkJCSJob29rcyI6ICJsb2dzLGNvbXBvc2UgbG9ncyxjb21wb3NlIGF0dGFjaCxjb21wb3NlIHVwIgoJCX0sCgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9
type: kubernetes.io/dockerconfigjson
